#!/bin/bash

echo "init and update git submodules"

git submodule init
git submodule update

# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
files="bashrc vimrc vim zshrc oh-my-zsh gitconfig ghci"

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv -n ~/.$file ~/dotfiles_old/
    rm ~/.$file
    echo "Creating symlink to $file in home directory."
    ln -sf $dir/$file ~/.$file
done

mkdir ~/.vim/backup
mkdir ~/.vim/undodir
touch ~/.zshrc.local

./osxsetup
